name: Maven CI - Spring PetClinic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£Checkout source
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3Ô∏è‚É£ Build + Unit Tests
      - name: Build with Maven
        run: mvn clean verify

      # 4Ô∏è‚É£ Upload Unit Test Results
      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/

      # 5Ô∏è‚É£ Upload Build Artifact (JAR)
      - name: Upload Application Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-jar
          path: target/*.jar

    #   # 6Ô∏è‚É£ Telegram Notification ‚Äì Test Result
    #   - name: Notify Telegram (Test Result)
    #     if: always()
    #     run: |
    #       STATUS="${{ job.status }}"
    #       MESSAGE="üß™ Spring PetClinic CI\nTests Status: ${STATUS}\nRepo: ${{ github.repository }}\nRun: ${{ github.run_id }}"
    #       curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
    #         -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    #         -d text="$MESSAGE"

    #   # 7Ô∏è‚É£ Telegram Notification ‚Äì Artifact Uploaded
    #   - name: Notify Telegram (Artifact Uploaded)
    #     if: success()
    #     run: |
    #       MESSAGE="üì¶ Artifact Uploaded Successfully\nRepo: ${{ github.repository }}\nWorkflow: ${{ github.workflow }}"
    #       curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
    #         -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    #         -d text="$MESSAGE"
